name: walrus
version: 0.6
date: 2018-06-21
description: |
    A new approach to proving hyperbolicity

authors:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

maintainers:
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "datastructures"
      version: "0.1.2"
      url: "https://gap-packages.github.io/datastructures"
    - name: "digraphs"
      version: ">= 0.10"
      url: "https://gap-packages.github.io/Digraphs"
    - name: "kbmag"
      version: ">= 1.5.4"
      url: "https://gap-packages.github.io/kbmag"

suggested-pkgs:
    - name: "profiling"
      version: " >= 1.3.0"
      url: "http://gap-packages.github.io/profiling/"

www: https://gap-packages.github.io/walrus
readme: README.md
packageinfo: https://gap-packages.github.io/walrus/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/walrus/releases/download/v0.6/walrus-0.6.tar.gz

abstract: |
    An implementation of hyperbolicity testing using an ideas
    by Richard Parker, Derek Holt, Colva Roney-Dougal, Max Neunhöffer,
    and probably quite a few more

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Finitely Generated, group, monoid, hyperbolic.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Pfe18</span>]   <b class='BibAuthor'>Pfeiffer, M.</b>,
     <i class='BibTitle'>walrus, A new approach to proving hyperbolicity,
             Version 0.6</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/walrus">https://gap-packages.github.io/walrus</a></span>.
    </p>
    

bibtex: |
    @misc{ walrus0.6,
      author =           {Pfeiffer, M.},
      title =            {{walrus}, A new approach to proving hyperbolicity, {V}ersion 0.6},
      month =            {Jun},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/walrus} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{walrus}}},
      keywords =         {Finitely Generated; group; monoid; hyperbolic},
      printedkey =       {Pfe18}
    }

